steps:
  - id: docker_build
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_IMAGE_NAME}:${_IMAGE_TAG}', '.' ]

images: [ '${_IMAGE_NAME}:${_IMAGE_TAG}' ]
timeout: 1800s
substitutions:
  _IMAGE_NAME: 'asia.gcr.io/kagglemuggle/osic-pulmonary-fibrosis'
  _IMAGE_TAG: '1.0'
